[build]
  command = "yarn build"
  publish = "dist"

[[headers]]
  for = "/*.obj"
  [headers.values]
    Content-Type = "text/plain"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions/"

  [functions.list-objs]
